### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by xelser** [xelser/edge-gtk#1]
Design tweaks
- [x] Make Firefox in dark modes more readable. (fixed in 7dcd811 and bd282a8)
- [x] Make colors in light modes more visible.
- [x] Consistent geometry

Ports
- [ ] Official Flatpak support
- [ ] Gradience theme for GNOME
- [ ] Openbox theme (planned)
